_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50 
  ROI_HEADS.NUM_CLASSES: 1
 SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  IMS_PER_BATCH: 2
  BASE_LR: 0.00025
  MAX_ITER: 1000
  STEPS: []
DATASETS:
  TRAIN: ("train")
  TEST: ()
DATALOADER:
   NUM_WORKERS: 2
OUTPUT_DIR: "./output"
 
